/**
  ******************************************************************************
  * @file    system_hk32m07x.c
  * @version V1.0.1
  * @date    2024-12-13
  * @brief   CMSIS Cortex-M0 Device Peripheral Access Layer System Source File.
  *          This file contains the system clock configuration for hk32m07x devices,
  *          and is generated by the clock configuration tool
  *
  * 1.  This file provides two functions and one global variable to be called from
  *     user application:
  *      - SystemInit(): Setups the system clock (System clock sourceand Divider factors
  *                       AHB/APBx prescalers and Flash settings),depending on the
  *                      configuration made in the clock xls tool.
  *                      This function is called at startup just after reset and
  *                      before branch to main program. This call is made inside
  *                      the "startup_hk32m07x.s" file.
  *
  *      - SystemCoreClock variable: Contains the core clock (HCLK), it can be used
  *                                  by the user application to setup the SysTick
  *                                  timer or configure other parameters.
  *
  *      - SystemCoreClockUpdate(): Updates the variable SystemCoreClock and must
  *                                 be called whenever the core clock is changed
  *                                 during program execution.
  *
  * 2. After each device reset the HSI (64 MHz Range) is used as system clock source.
  *    Then SystemInit() function is called, in "startup_hk32m07x.s" file, to
  *    configure the system clock before to branch to main program.
  *
  * 3. If the system clock source selected by user fails to startup, the SystemInit()
  *    function will do nothing and HSI still used as system clock source. User can
  *    add some code to deal with this issue inside the SetSysClock() function.
  *
  * 5. This file configures the system clock as follows:
  *=============================================================================
  *=============================================================================
  *        SYSCLK(Hz)                             | 64000000
  *-----------------------------------------------------------------------------
  *        HCLK(Hz)                               | 64000000
  *-----------------------------------------------------------------------------
  *        AHB Prescaler                          | 1
  *-----------------------------------------------------------------------------
  *        APB Prescaler                          | 1
  *-----------------------------------------------------------------------------
  *        HSI Frequency(Hz)                      | 64000000
  *----------------------------------------------------------------------------
  *        PREDIV                                 | 1
  *-----------------------------------------------------------------------------
  *        Flash Latency(WS)                      | 2
  *-----------------------------------------------------------------------------
  *        Prefetch Buffer                        | ON
  *-----------------------------------------------------------------------------
  ******************************************************************************
  */

/** @addtogroup CMSIS
  * @{
  */

/** @addtogroup hk32m07x_system
  * @{
  */

/** @addtogroup hk32m07x_System_Private_Includes
  * @{
  */

#include "hk32m07x.h"
#include "hk32m07x_flash.h"
#include "hk32m07x_gpio.h"
#include "hk32m07x_conf.h"
/**
  * @}
  */

/*******************************************************************************
*  Clock Definitions
*******************************************************************************/

#if( SYSCLK_SOURCE == SYSCLK_SRC_HSI8M)
    uint32_t SystemCoreClock         = SYSCLK_FREQ_HSI_8M;                         /*!< System Clock Frequency (Core Clock) */
    static void SetSysClockToHSI_8M(void);
    #elif( SYSCLK_SOURCE == SYSCLK_SRC_HSI64M)
    uint32_t SystemCoreClock         = SYSCLK_FREQ_HSI_64M;                        /*!< System Clock Frequency (Core Clock) */
    static void SetSysClockToHSI_64M(void);
    #elif( SYSCLK_SOURCE == SYSCLK_SRC_EXTCLK_IO)
    uint32_t SystemCoreClock         = SYSCLK_FREQ_EXTCLK;                         /*!< System Clock Frequency (Core Clock) */
    static void SetSysClockToEXTCLK(void);
    #elif( SYSCLK_SOURCE == SYSCLK_SRC_LSI)
    uint32_t SystemCoreClock         = SYSCLK_FREQ_LSI;                         /*!< System Clock Frequency (Core Clock) */
    static void SetSysClockToLSI(void);
#endif

/** @addtogroup hk32m07x_System_Private_Variables
  * @{
  */
__I uint8_t AHBPrescTable[16] = {0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 3, 4, 6, 7, 8, 9};

/**
  * @}
  */

/** @addtogroup hk32m07x_System_Private_FunctionPrototypes
  * @{
  */

static void SetSysClock(void);

/**
  * @}
  */

/** @addtogroup hk32m07x_System_Private_Functions
  * @{
  */

/**
  * @brief  Setup the microcontroller system.
  *         Initialize the Embedded Flash Interface, the PLL and update the
  *         SystemCoreClock variable.
  * @param  None
  * @retval None
  */
void SystemInit (void)
{
    /* Set HSION bit */
    RCC->CR |= (uint32_t)0x00000001;

    /* Reset SW[1:0], HPRE[3:0], PPRE[2:0] ,MCO[2:0] bits */
    RCC->CFGR &= (uint32_t)0x0E00000C;

    /* Reset ESSS bit */
    RCC->CFGR4 &= ~ RCC_CFGR4_ESSS;

    /* Disable all interrupts */
    RCC->CIR = 0x00000000;

    /* Configure the System clock frequency, AHB/APBx prescalers and Flash settings */
    SetSysClock();

}

/**
  * @brief  Update SystemCoreClock according to Clock Register Values
  *         The SystemCoreClock variable contains the core clock (HCLK), it can
  *         be used by the user application to setup the SysTick timer or configure
  *         other parameters.
  *
  * @note   Each time the core clock (HCLK) changes, this function must be called
  *         to update SystemCoreClock variable value. Otherwise, any configuration
  *         based on this variable will be incorrect.
  *
  * @note   - The system frequency computed by this function is not the real
  *           frequency in the chip. It is calculated based on the predefined
  *           constant and the selected clock source:
  *
  *           - If SYSCLK source is HSI, SystemCoreClock will contain the HSI_VALUE(*)
  *
  *           - If SYSCLK source is HSE, SystemCoreClock will contain the HSE_VALUE(**)
  *
  *           - If SYSCLK source is PLL, SystemCoreClock will contain the HSE_VALUE(**)
  *             or HSI_VALUE(*) multiplied/divided by the PLL factors.
  *
  *         (*) HSI_VALUE is a constant defined in hk32m07x.h file (default value
  *             8 MHz) but the real value may vary depending on the variations
  *             in voltage and temperature.
  *
  *         (**) HSE_VALUE is a constant defined in hk32m07x.h file (default value
  *              8 MHz), user has to ensure that HSE_VALUE is same as the real
  *              frequency of the crystal used. Otherwise, this function may
  *              have wrong result.
  *
  *         - The result of this function could be not correct when using fractional
  *           value for HSE crystal.
  * @param  None
  * @retval None
  */
void SystemCoreClockUpdate (void)
{
    uint32_t tmp = 0;

    /* Get SYSCLK source -------------------------------------------------------*/
    tmp = RCC->CFGR & RCC_CFGR_SWS;

    switch (tmp)
    {
        case 0x00:  /* HSI used as system clock */
            SystemCoreClock = HSI8_VALUE;
            break;

        default: /* HSI used as system clock */
            SystemCoreClock = HSI64_VALUE;
            break;
    }

    /* Compute HCLK clock frequency ----------------*/
    /* Get HCLK prescaler */
    tmp = AHBPrescTable[((RCC->CFGR & RCC_CFGR_HPRE) >> 4)];
    /* HCLK clock frequency */
    SystemCoreClock >>= tmp;
}

/**
  * @brief  Configures the System clock frequency, AHB/APBx prescalers and Flash
  *         settings.
  * @note   This function should be called only once the RCC clock configuration
  *         is reset to the default reset state (done in SystemInit() function).
  * @param  None
  * @retval None
  */
static void SetSysClock(void)
{
#if defined SYSCLK_FREQ_HSI_8M
    SetSysClockToHSI_8M();
#elif defined SYSCLK_FREQ_HSI_64M
    SetSysClockToHSI_64M();
#elif defined SYSCLK_FREQ_EXTCLK
    SetSysClockToEXTCLK();
#elif defined SYSCLK_FREQ_LSI
    SetSysClockToLSI();
#endif
    /* If none of the define above is enabled, the HSI is used as System clock
        source (default after reset) */
}

#if defined SYSCLK_FREQ_EXTCLK
static void SetSysClockToEXTCLK(void)
{
    /* SYSCLK, HCLK and PCLK1 configuration */
    /* Enable EXCLK */
    //enable EXTIO PB15/PA0
    /* Configure PA0 as CLOCK input */
    GPIO_InitTypeDef GPIO_InitStructure;

    RCC_AHBPeriphClockCmd(RCC_AHBPeriph_GPIOA, ENABLE);

    GPIO_InitStructure.GPIO_Mode  = GPIO_Mode_AF;
    GPIO_InitStructure.GPIO_Speed = GPIO_Speed_Level_4;
    GPIO_InitStructure.GPIO_OType = GPIO_OType_PP;
    GPIO_InitStructure.GPIO_PuPd  = GPIO_PuPd_UP;
	GPIO_InitStructure.GPIO_Schmit =GPIO_Schmit_Disable;	
    GPIO_InitStructure.GPIO_Pin = GPIO_Pin_0;
    GPIO_Init(GPIOA, &GPIO_InitStructure);
    GPIO_PinAFConfig(GPIOA, GPIO_PinSource0, GPIO_AF_7);

    /*CLOCK select */
    RCC->CFGR4 &= (uint32_t)((uint32_t)~(RCC_CFGR4_EXTCLK_SEL));
    RCC->CFGR4 |= (uint32_t)0x0 << RCC_CFGR4_EXTCLK_SEL_Pos;

    //    RCC_AHBPeriphClockCmd(RCC_AHBPeriph_GPIOB, ENABLE);

    //    GPIO_InitStructure.GPIO_Mode  = GPIO_Mode_AF;
    //    GPIO_InitStructure.GPIO_Speed = GPIO_Speed_Level_4;
    //    GPIO_InitStructure.GPIO_OType = GPIO_OType_PP;
    //    GPIO_InitStructure.GPIO_PuPd  = GPIO_PuPd_UP;
	//    GPIO_InitStructure.GPIO_Schmit =GPIO_Schmit_Disable;
    //    GPIO_InitStructure.GPIO_Pin = GPIO_Pin_15;
    //    GPIO_Init(GPIOB, &GPIO_InitStructure);
    //    GPIO_PinAFConfig(GPIOB, GPIO_PinSource15, GPIO_AF_7);

    //    /*CLOCK select */
    //    RCC->CFGR4 &= (uint32_t)((uint32_t)~(RCC_CFGR4_EXTCLK_SEL));
    //    RCC->CFGR4 |= (uint32_t)0x1 << RCC_CFGR4_EXTCLK_SEL_Pos;

    /* Enable Prefetch Buffer */
    FLASH->ACR |= FLASH_ACR_PRFTBE;

    /* Flash wait state */
    uint32_t FlashAcr = FLASH->ACR;
    FlashAcr &= (uint32_t)((uint32_t)~FLASH_ACR_LATENCY);
    FlashAcr |= (uint32_t)FLASH_Latency_1;
    FLASH->ACR = FlashAcr;

    /* HCLK = SYSCLK */
    RCC->CFGR &= (uint32_t)((uint32_t)~RCC_CFGR_HPRE);
    RCC->CFGR |= (uint32_t)RCC_SYSCLK_Div1;

    /* PCLK1 = HCLK */
    RCC->CFGR &= (uint32_t)((uint32_t)~RCC_CFGR_PPRE);
    RCC->CFGR |= (uint32_t)RCC_HCLK_Div1;


    RCC->CFGR4 &= (uint32_t)((uint32_t)~(RCC_CFGR4_ESW));
    RCC->CFGR4 |= (uint32_t)0x4 << RCC_CFGR4_ESW_Pos;
    /* Select EXTCLK as system clock source */
    RCC->CFGR4 |= RCC_CFGR4_ESSS;

    /* Wait till EXTCLK is used as system clock source */
    while ((RCC->CFGR4 & (uint32_t)RCC_CFGR4_ESWS) != ((uint32_t)0x4 << RCC_CFGR4_ESWS_Pos))
    {
    }
}
#elif defined SYSCLK_FREQ_HSI_64M
static void SetSysClockToHSI_64M(void)
{
    __IO uint32_t StartUpCounter = 0, HSIStatus = 0;

    /* SYSCLK, HCLK and PCLK1 configuration */
    /* Enable HSI */
    RCC->CR |= ((uint32_t)RCC_CR_HSION);

    /* Wait till HSI is ready and if Time out is reached exit */
    do
    {
        HSIStatus = RCC->CR & RCC_CR_HSIRDY;
        StartUpCounter++;
    } while ((HSIStatus == 0) && (StartUpCounter != HSI_STARTUP_TIMEOUT));

    if ((RCC->CR & RCC_CR_HSIRDY) != RESET)
    {
        HSIStatus = (uint32_t)0x01;
    }
    else
    {
        HSIStatus = (uint32_t)0x00;
    }

    if (HSIStatus == (uint32_t)0x01)
    {
        /* Enable Prefetch Buffer */
        FLASH->ACR |= FLASH_ACR_PRFTBE;

        /* Flash 2 wait state */
        uint32_t FlashAcr = FLASH->ACR;
        FlashAcr &= (uint32_t)((uint32_t)~FLASH_ACR_LATENCY);
        FlashAcr |= (uint32_t)FLASH_Latency_2;
        FLASH->ACR = FlashAcr;

        /* HCLK = SYSCLK */
        RCC->CFGR &= (uint32_t)((uint32_t)~RCC_CFGR_HPRE);
        RCC->CFGR |= (uint32_t)RCC_SYSCLK_Div1;

        /* PCLK1 = HCLK */
        RCC->CFGR &= (uint32_t)((uint32_t)~RCC_CFGR_PPRE);
        RCC->CFGR |= (uint32_t)RCC_HCLK_Div1;

        RCC->CFGR4 &= ~(RCC_CFGR4_ESW);
        RCC->CFGR4 |= (uint32_t)0x2 << RCC_CFGR4_ESW_Pos;

        /* Select HSI64 as system clock source */
        RCC->CFGR4 |= RCC_CFGR4_ESSS;

        /* Wait till HSI is used as system clock source */
        while ((RCC->CFGR4 & (uint32_t)RCC_CFGR4_ESWS) != ((uint32_t)0x2 << RCC_CFGR4_ESWS_Pos))
        {
            __NOP();
            __NOP();
            __NOP();
            __NOP();
            __NOP();
        }
    }
    else
    {
        /* If fails to start-up */
    }
}

#elif defined SYSCLK_FREQ_HSI_8M
static void SetSysClockToHSI_8M(void)
{
    __IO uint32_t StartUpCounter = 0, HSIStatus = 0;

    /* SYSCLK, HCLK, PCLK2 and PCLK1 configuration */
    /* Enable HSI */
    RCC->CR |= ((uint32_t)RCC_CR_HSION);

    /* Wait till HSE is ready and if Time out is reached exit */
    do
    {
        HSIStatus = RCC->CR & RCC_CR_HSIRDY;
        StartUpCounter++;
    } while ((HSIStatus == 0) && (StartUpCounter != HSI_STARTUP_TIMEOUT));

    if ((RCC->CR & RCC_CR_HSIRDY) != RESET)
    {
        HSIStatus = (uint32_t)0x01;
    }
    else
    {
        HSIStatus = (uint32_t)0x00;
    }

    if (HSIStatus == (uint32_t)0x01)
    {
        /* Enable Prefetch Buffer */
        FLASH->ACR |= FLASH_ACR_PRFTBE;

        /* Flash 0 wait state */
        uint32_t FlashAcr = FLASH->ACR;
        FlashAcr &= (uint32_t)((uint32_t)~FLASH_ACR_LATENCY);
        FlashAcr |= (uint32_t)FLASH_Latency_0;
        FLASH->ACR = FlashAcr;

        /* HCLK = SYSCLK */
        RCC->CFGR &= (uint32_t)((uint32_t)~RCC_CFGR_HPRE);
        RCC->CFGR |= (uint32_t)RCC_SYSCLK_Div1;

        /* PCLK1 = HCLK */
        RCC->CFGR &= (uint32_t)((uint32_t)~RCC_CFGR_PPRE);
        RCC->CFGR |= (uint32_t)RCC_HCLK_Div1;

        /* Select HSI as system clock source */
        RCC->CFGR4 &= ~RCC_CFGR4_ESSS;

        RCC->CFGR &= (uint32_t)((uint32_t)~(RCC_CFGR_SW));
        RCC->CFGR |= (uint32_t)0x0 << RCC_CFGR_SW_Pos;

        /* Wait till HSI is used as system clock source */
        while ((RCC->CFGR & (uint32_t)RCC_CFGR_SWS) != ((uint32_t)0x0 << RCC_CFGR_SWS_Pos))
        {
        }
    }
    else
    {
        /* If fails to start-up */
    }
}



#elif defined SYSCLK_FREQ_LSI
static void SetSysClockToLSI(void)
{
    __IO uint32_t StartUpCounter = 0, LSIStatus = 0;

    /* SYSCLK, HCLK, PCLK2 and PCLK1 configuration */

    /* Enable LSI */
    RCC->CSR |= RCC_CSR_LSION;

    /* Wait till HSE is ready and if Time out is reached exit */
    do
    {
        LSIStatus = RCC->CSR & RCC_CSR_LSIRDY;
        StartUpCounter++;
    } while ((LSIStatus == 0) && (StartUpCounter != 0xFFFF));

    if ((RCC->CSR & RCC_CSR_LSIRDY) != RESET)
    {
        LSIStatus = (uint32_t)0x01;
    }
    else
    {
        LSIStatus = (uint32_t)0x00;
    }

    if (LSIStatus == (uint32_t)0x01)
    {
        /* Enable Prefetch Buffer */
        FLASH->ACR |= FLASH_ACR_PRFTBE;

        /* Flash 0 wait state */
        uint32_t FlashAcr = FLASH->ACR;
        FlashAcr &= (uint32_t)((uint32_t)~FLASH_ACR_LATENCY);
        FlashAcr |= (uint32_t)FLASH_Latency_0;
        FLASH->ACR = FlashAcr;

        /* HCLK = SYSCLK */
        RCC->CFGR &= (uint32_t)((uint32_t)~RCC_CFGR_HPRE);
        RCC->CFGR |= (uint32_t)RCC_SYSCLK_Div1;

        /* PCLK1 = HCLK */
        RCC->CFGR &= (uint32_t)((uint32_t)~RCC_CFGR_PPRE);
        RCC->CFGR |= (uint32_t)RCC_HCLK_Div1;

        /* Select LSI as system clock source */
        RCC->CFGR4 |= RCC_CFGR4_ESSS;

        RCC->CFGR4 &= ~(RCC_CFGR4_ESW);
        RCC->CFGR4 |= (uint32_t)0x1 << RCC_CFGR4_ESW_Pos;

        /* Wait till HSI is used as system clock source */
        while ((RCC->CFGR4 & (uint32_t)RCC_CFGR4_ESWS) != ((uint32_t)0x1 << RCC_CFGR4_ESWS_Pos))
        {
        }
    }
    else
    {
        /* If fails to start-up */
    }
}

#endif
